import { useState } from 'react'
import Header from '../../components/Header';
import Avatar from '../../components/Avatar';
import BackButton from '../../components/BackButton';

import "../../css/TowardsSOM.css";

import tamIcon from "../../assets/img/tam-icon.png";
import samIcon from "../../assets/img/sam-icon.png";
import cspIcon from "../../assets/img/csp-icon.png";
import { useNavigate } from 'react-router-dom';

function TowardsSOM() {

    const [onNext, setOnNext] = useState(false)

    const navigate = useNavigate()

    function Next() {
        setOnNext(true)
    }

    function handleNoClick() {
        navigate("/Biz-Sim-V2/CSP")
    }
    function handleYesClick() {
        navigate("/Biz-Sim-V2/SOM")
    }
    return (
        <div>

            <Header />
            <Avatar />
            <BackButton />
            <div className='indicatorIcon-container'>
                <div className='Icon-div' onClick={() => navigate('/Biz-Sim-V2/tam-calculation')}>
                    <img src={tamIcon} alt="TAM-Icon" className="Tam-Icon" />
                </div>
                <div className='Icon-div' onClick={() => navigate('/Biz-Sim-V2/sam-calculation')}>
                    <img src={samIcon} alt="SAM-Icon" className="SAM-Icon" />
                </div>
                <div className='Icon-div' onClick={() => navigate('/Biz-Sim-V2/csp')}>
                    <img src={cspIcon} alt="CSP-Icon" className="CSP-Icon" />
                </div>
            </div>
            <div className='towards-som-container'>
                {!onNext &&
                    <div className='towardsSOMHeaders'>
                        <div className=''>
                            Now, Serviceable Addressable Market is that portion of the Total addressable market (TAM) that your business can target and serve with its current products, services, and geographic reach based on your business model and capabilities, but it does not consider competition or market barriers
                        </div>
                        <br />
                        <div className=''>
                            Which means that the Yearly Expenditure by SAM value that we calculated in the last section might not be a realistic value of the revenue that you generate from your business
                        </div>
                    </div>}
                {onNext &&
                    <div className='towardsSOMHeaders'>
                        <div >
                            So how do we get a realistic estimate of the revenue generated by your business?
                        </div>
                        <br />
                        <div >
                            The answer to that question is Serviceable Obtainable Market (SOM), in which we assume an estimate percentage of the SAM value, which gives us an assumed subset population that your business will be able to cater to considering competition or other market barriers

                            In short, SAM is the reachable market segment, while SOM is the realistically achievable share within that segment.
                        </div>
                        <br />
                        <div className='towardsSOMready' >
                            Are you ready to move on to SOM?
                        </div>
                        <div className='towardsSOM-yesno-container'>
                            <div className="no-div">
                                <button className='' onClick={handleNoClick}>NO</button>
                                <div className='towardsSOMready'>Go Back to CSP</div>
                            </div>
                            <div className="no-div">
                                <button className='' onClick={handleYesClick}>YES</button>
                                <div className='towardsSOMready'>Proceed to SOM</div>
                            </div>
                        </div>
                        <div>Click here to learn more about SOM</div>

                    </div>}
                <button className='towardsSOM-NextBTN' onClick={Next}>NEXT</button>
            </div>


        </div>
    )
}

export default TowardsSOM;