import React, { useEffect, useState } from 'react'
import Header from '../../components/Header'
import BackButton from '../../components/BackButton'
import { motion, AnimatePresence } from 'framer-motion';
import '../../css/OpEx.css'



import tamIcon from "../../assets/img/tam-icon.png";
import samIcon from "../../assets/img/sam-icon.png";
import cspIcon from "../../assets/img/csp-icon.png";
import somIcon from "../../assets/img/som-icon.png";
import Footer from '../../components/Footer';
import NumberToWords from '../../components/NumberToWords';
import CustomTextField from '../../components/CustomTextField';
import { useNavigate } from 'react-router-dom';

const Slide = ({ children, keyName }: { children: React.ReactNode; keyName: string }) => (
    <AnimatePresence mode="wait">
        <motion.div
            key={keyName}
            initial={{ opacity: 0, x: -50 }}
            animate={{ opacity: 1, x: 0 }}
            // exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.5 }}
            style={{ overflowX: "auto", whiteSpace: "nowrap" }}
        >
            {children}
        </motion.div>
    </AnimatePresence>
);

function OpEx() {

    const [rows, setRows] = useState([
        { id: 1, ExpenseName: '', TypeOfExpense: '', ValueOfExpense: '' },
        { id: 2, ExpenseName: '', TypeOfExpense: '', ValueOfExpense: '' },
        { id: 3, ExpenseName: '', TypeOfExpense: '', ValueOfExpense: '' },
    ]);
    const [errorMessage, setErrorMessage] = useState('');
    const [TotalOpEx, setTotalOpEx] = useState('');

    const [SAM, setSAM] = useState("");

    const [showOpExIcon, setshowOpExIcon] = useState(false);
    const [showOpExIconText, setshowOpExIconText] = useState(false);

    const [isHoveredRow, setisHoveredRow] = useState("");

    const navigate = useNavigate()

    // helper Functions

    // helper Functions End

    // Table functions
    const handleDeleteRow = (id: number) => {
        if (rows.length === 1) {
            setErrorMessage('Please enter at least one segment.');
            return;
        }
        setRows(rows.filter(row => row.id !== id));
    };

    const handleExpenseNameChange = (id: number, value: string) => {
        const updatedRows = rows.map(row =>
            row.id === id ? { ...row, ExpenseName: value } : row
        );
        setRows(updatedRows);
    };

    const handleExpenseTypeChange = (id: number, value: string) => {
        const updatedRows = rows.map(row =>
            row.id === id ? { ...row, TypeOfExpense: value } : row
        );
        setRows(updatedRows);
    }

    const handleExpenseValueChange = (id: number, value: string) => {
        const updatedRows = rows.map(row =>
            row.id === id ? { ...row, ValueOfExpense: value } : row
        );
        setRows(updatedRows);
    };

    const handleAddRow = () => {
        const newRow = {
            id: rows.length ? rows[rows.length - 1].id + 1 : 1,
            ExpenseName: '',
            TypeOfExpense: '',
            ValueOfExpense: '',
        };
        setRows([...rows, newRow]);
    };

    const handleSaveDetails = () => {
        const allFieldsFilled = rows.every(row => row.ExpenseName !== '' && row.ValueOfExpense !== '' && row.TypeOfExpense !== '');
        if (!allFieldsFilled) {
            setErrorMessage('Please enter details in all cells.');
            return;
        }
        setErrorMessage('');
        const total = rows.reduce((total, row) => total + parseInt(row.ValueOfExpense), 0);
        setTotalOpEx(total.toString());
        localStorage.setItem('OpEx', total.toString());
        localStorage.setItem('OpExDB', JSON.stringify(rows));
    };



    // Table functions end


    const footerTexts = [
        "Here in the section of Serviceable Obtainable Market (SOM), the first thing you will see is that we have displayed the value of SAM which we had calculated in the earlier section. Now remember this is an estimate of customers that will be catered by your business without any competition and other market barriers.",
        "Now, based on what you have learned about Serviceable Addressable Market, Serviceable Obtainable Market, the general ratio between the two, and on what kind of competitors and other market barriers you may face in your business, enter an educated estimate value in the field and press “Enter” or click on “SUBMIT”.",
        "Now three values regarding the daily, monthly and yearly expenditure by customer has come up on the screen, which looks similar to what we had in the SAM section. The difference here is that the values presented above are a practical estimation of revenue generated by your business. So do you think with this revenue your business will be profitable?",
        "Great! You have successfully defined and calculated the size of the Serviceable Obtainable Market (SOM) for your business and a practical estimate of the revenue generated. To mark this milestone an icon signifying the same will be added to the sidebar, which you can use to navigate back to SOM if you want to make any changes later.",
    ];


    return (
        <div>
            <Header />
            <BackButton topOffset='10vh' />
            <div className='indicatorIcon-container'>
                <div className='Icon-div'>
                    <img src={tamIcon} alt="TAM-Icon" className="Tam-Icon" />
                </div>
                <div className='Icon-div'>
                    <img src={samIcon} alt="SAM-Icon" className="Tam-Icon" />
                </div>
                <div className='Icon-div'>
                    <img src={cspIcon} alt="CSP-Icon" className="CSP-Icon" />
                </div>
                <div className='Icon-div'>
                    <img src={somIcon} alt="SOM-Icon" className="SOM-Icon" />
                </div>
                {/* Animate the icon entry */}
                <div className='Icon-div'>
                    <AnimatePresence mode="wait">
                        {showOpExIcon ? (

                            <motion.img
                                key="SOM-img"
                                src={somIcon}
                                alt="SOM-Icon"
                                className="SOM-Icon"
                                initial={{ opacity: 0, x: -50 }}
                                animate={{ opacity: 1, x: 0 }}
                                exit={{ opacity: 0, x: -50 }}
                                transition={{ duration: 1 }}
                            />

                        ) : <div></div>}
                    </AnimatePresence>
                    {/* Animate the text entry/exit */}
                    <AnimatePresence mode="wait">
                        {showOpExIconText && (
                            <motion.span
                                key="SOM-Icon-Text"
                                initial={{ opacity: 0, x: -100 }}
                                animate={{ opacity: 1, x: 0 }}
                                exit={{ opacity: 0, x: -100 }}
                                transition={{ duration: 1 }}
                            >
                                Operational Expenditure
                            </motion.span>
                        )}
                    </AnimatePresence>
                </div>
            </div>
            <div className="table-container">
                <h1>Operational Expenditure</h1>
                <table className="table">
                    <thead>
                        <tr>

                            <th></th>{/* Delete row column */}
                            <th>Name of the Expense</th>
                            <th>Type of Expense</th>
                            <th>Value of the Expense</th>
                            {<th></th>}{/* NumberToWords header */}
                        </tr>
                    </thead>
                    <tbody>
                        {rows.map(row => (
                            <tr key={row.id}>
                                <td>
                                    <button className="delete-button" onClick={() => handleDeleteRow(row.id)}>-</button>
                                </td>
                                <td>
                                    <CustomTextField
                                        value={row.ExpenseName}
                                        type='text'
                                        placeholder='Enter Name'
                                        onChange={(value) => handleExpenseNameChange(row.id, value)}
                                    />
                                </td>
                                <td>
                                    {/* Expense type toggle */}
                                    <div className="expense-type-toggle">
                                        <button
                                            // type="button"
                                            className={`expense-type-btn left ${row.TypeOfExpense === 'fixed' ? 'selected' : ''}`}
                                            onClick={() => handleExpenseTypeChange(row.id, 'fixed')}
                                        >
                                            Fixed
                                        </button>

                                        <button
                                            // type="button"
                                            className={`expense-type-btn right ${row.TypeOfExpense === 'variable' ? 'selected' : ''}`}
                                            onClick={() => handleExpenseTypeChange(row.id, 'variable')}
                                        >
                                            Variable
                                        </button>
                                    </div>
                                </td>
                                <td>
                                    <div
                                        onMouseEnter={() => setisHoveredRow(`${row.id}`)}
                                        onMouseLeave={() => setisHoveredRow("")}
                                    >
                                        <CustomTextField
                                            value={row.ValueOfExpense}
                                            type='number'
                                            placeholder='Enter Value'
                                            onChange={(value) => handleExpenseValueChange(row.id, value)}
                                        />
                                    </div>
                                </td>

                                <td >
                                    {isHoveredRow == `${row.id}` &&
                                        <Slide keyName={"NumberToWords-row:" + row.id}                                    >
                                            <NumberToWords value={row.ValueOfExpense} />
                                        </Slide>
                                    }
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
                {errorMessage && <div className="error-message">{errorMessage}</div>}
                <div className="button-container">
                    <button className="add-button" onClick={handleAddRow}>ADD EXPENSE</button>
                    {<button className="save-button" onClick={handleSaveDetails}>SAVE DETAILS</button>}
                </div>


                <div className="total-size-container">
                    {/* <span className="total-size-clear-icon" onClick={handleClearTotal}>x</span> */}
                    <span className="total-size-words"><NumberToWords value={SAM.toString()} /></span>
                    <input
                        type="text"
                        value={TotalOpEx}
                        readOnly
                        className="total-size-field"
                    />
                </div>

            </div>



            <Footer texts={footerTexts} />
        </div>
    )
}

export default OpEx